language: node_js
node_js:
- '0.12'
- 4.2
- stable
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: wVp9uLxpSlV4QKLTBmotiqDn/E18tR9LmT5r5wSRFKg6Ed/TvmWDBgZTl0wuyQme8ZZf5LBoRKUUTf8mGm9vIi/IZOesvSqChPlTRPGeHgaM1jIE4sTvn/bCNNvx86YcLuFWOIpO19It3m1wjqEXnslhuTsZEjEEqbhO3qCpDi4=
  on:
    tags: true
    repo: nfriedly/node-unblocker
